### ISSUE TITLE
Go 1.3.3 is available

### ISSUE THREAD

**Issue by drewwells** [nathany/vagrant-gopher#3]
I've had pretty good luck with 1.4, so maybe it's best to just skip straight ahead to 1.4!

**Comment by drewwells** [comment]
https://groups.google.com/forum/#!topic/golang-nuts/MYS5MkDF5_A
https://blog.golang.org/go1.4

**Comment by nathany** [comment]
working on an update right now

**Comment by drewwells** [comment]
awesome! :+1:
